Settings:
  Application:
    Name: OpenGL Engine
    StartupScene: Assets\Scenes\Test.scene
    Version:
      Major: 0
      Minor: 0
      Patch: 0
    Maximized: true
    DebugMode: false
    EscapeClosesApp: false
    LogToFile: false
  Audio:
    Volume:
      Master: 1
      Ambience: 1
      Effects: 1
      Music: 1
      Voices: 1
      MuteAll: false
    Device:
      InputDeviceID: 3
      OutputDeviceID: 2
      SampleRate: 48000
      BufferSize: 256
      PassThrough: false
  Editor:
    Appearance:
      Theme: Excellency
      FontSize: 13
      UIScale: 1
      ColumnWidth: 150
      ProjectWindow:
        IconSize: 64
        IconPadding: 24
    SceneCamera:
      Position:
        - 0
        - 0
        - 5
      Yaw: -90
      Pitch: 0
      FOV: 60
      NearClip: 0.1
      FarClip: 1000
      MovementSpeed: 2
      FastMovementSpeed: 5
      RotationSpeed: 2
      ZoomSpeed: 2
      Smoothing: 5
      InvertZoom: false
    Windows:
      ShowAbout: false
      ShowGame: true
      ShowHierarchy: true
      ShowInspector: true
      ShowProject: true
      ShowScene: true
      ShowSettings: false
      ShowStatistics: false
    AutoSaveInterval: 10
  Rendering:
    Engine: OpenGL
    Resolution:
      Width: 1920
      Height: 1080
      Scale: 1
    Mode: Windowed
    VSync: true
    LockFramerate: false
    TargetFrameRate: 0
  Navigation:
    MovementSpeed: 2
    FastMovementSpeed: 5
    RotationSpeed: 2
    ZoomSpeed: 2
    Smoothing: 5
    InvertZoom: false
  Export:
    ImageFormat: PNG
    ImageQuality: 100
    Folder: Export